"""Test helper functions for Voice tests.

This module re-exports helper functions from conftest.py for backward compatibility.
The actual UUID management is now dynamic (generated by the database) rather than
using hardcoded UUIDs.
"""

from __future__ import annotations

# Re-export from conftest - these use dynamic IDs populated by fixtures
from tests.conftest import (
    TAG_IDS,
    NOTE_IDS,
    TAG_UUIDS,
    NOTE_UUIDS,
    TEST_DEVICE_ID,
    uuid_to_hex,
    get_tag_uuid,
    get_tag_uuid_hex,
    get_note_uuid,
    get_note_uuid_hex,
)

__all__ = [
    "TAG_IDS",
    "NOTE_IDS",
    "TAG_UUIDS",
    "NOTE_UUIDS",
    "TEST_DEVICE_ID",
    "uuid_to_hex",
    "get_tag_uuid",
    "get_tag_uuid_hex",
    "get_note_uuid",
    "get_note_uuid_hex",
]
